w = 0
h = 0
floor = 0
vg = None
ct = None
grid = None
value_grid = None
player_pos = (0, 0)
basic_tiles = {}
message = None  # Current message to display to player
game_complete = False  # Set to True when player finishes the game